### ISSUE TITLE
Demo app impacted by turbolinks compatibility issue.

### ISSUE THREAD

**Issue by richlarcombe** [jhund/filterrific#103]
Having experienced what i thought was pagination related issues breaking the expected operation of Demo app.
It would appears the culprit was due to some 'ready event problems caused by Turbolinks5' (which is now installed by default)
Downgrading to using gem `'turbolinks', '~> 2.5.3'` fixed things up to some degree, filterriffic behaved better but there was still an issue with needing to double click pagination links.
Using [jquery.turbolinks](https://github.com/kossnocorp/jquery.turbolinks) then solved this.

Suggests that maybe a change in filterrific to ensure compatibility with turbolinks5 would be helpful if anyone has the time?

**Comment by genezys** [comment]
Turbolinks 5 has changed its events to `turbolinks:` instead of `page:`.

If you look at https://github.com/jhund/filterrific/blob/master/app/assets/javascripts/filterrific/filterrific-jquery.js#L83, you can see that Filterrific only listen to the `page:load` event and should also listen to `turbolinks:load` to be compatible with Turbolinks 5.

I will submit a PR for this change.

**Comment by genezys** [comment]
My bad, it appears that PR #87 already solved this issue.

**Comment by jhund** [comment]
This has been fixed with 2.1.2 release
