### ISSUE TITLE
Cascading Dropdowns for Filterrific

### ISSUE THREAD

**Issue by dragonzzz** [jhund/filterrific#48]
How do I do cascading dropdown in Filterrific
give that i have Domain -> Sector -> Subsector
I tried to initialize the select_options for Sector and Subsector to an empty set and then provide it with value once Domain has been selected. 

However in my model when I try to access 
filterrific :select_options => { :with_sector_id =>  Sector.options_for_select }
I get an error "wrong number of arguments (0 for 1)"

See example below. 

class Profile < ActiveRecord::Base
  filterrific :default_filter_params => { :sorted_by => 'created_at_desc' },
              :available_filters => %w[
                with_domain_id
                with_sector_id
                with_subsector_id
              ]
  scope :with_domain_id, lambda { |with_domain_id|
    # select and search for the content. 
    profile_expertises = Expertise.arel_table
    profile_searches = Profile.arel_table
    
    where(
        Expertise \
          .where(profile_expertises[:profile_id].eq(profile_searches[:id] )) \
          .where(profile_expertises[:domain_id].in([*with_domain_id].map(&:to_i))) \
          .exists
    )
    filterrific :select_options => { :with_sector_id =>  Sector.options_for_select }
---------------------------------------------------------------
class SearchesController < ApplicationController
  # GET /profiles
  # GET /profiles.json
  def index
    @filterrific = initialize_filterrific(
      Profile,
      params[:filterrific],
      :select_options => {
        sorted_by: Profile.options_for_sorted_by,
        with_domain_id: Domain.options_for_select,
        with_sector_id: [],
        with_subsector_id: [],
      }
    )

**Comment by dragonzzz** [comment]
Anyone able to help?

**Comment by jhund** [comment]
@dragonzzz I don't think you provided all source code required to answer this question. If I understand correctly, you need to change select options for filters dynamically, based on selection of a higher level filter. In other words, do you want to change the options for `Sector` when the selection for `Domain` changes? In that case, I suggest you use client side javascript code. This is outside of the scope of Filterrific and I suggest you look into jQuery or whichever JS approach you use.

**Comment by dragonzzz** [comment]
Yes that is exactly what I want to do. Using jquery to dynamically change the Sector values, Would it still work with Filterrific's ajax calls?

**Comment by dragonzzz** [comment]
And how would that work in conjunction with the form_for_filterrific view helper

**Comment by jhund** [comment]
@dragonzzz I would do the following:

* provide a hierarchical data structure in javascript that contains all domains, sectors and subsectors with id and name each so that you can use them as options for select. You could either load the whole structure at page load, or pull in data dynamically via AJAX from the jQuery event handler.
* add an observer to the `Domain` and `Sector` filter dropdowns. This observer would update the select options on the dependent filters every time it changes, using the hierarchical data structure mentioned above.
* you could use `form_for_filterrific` as documented with the only difference that I would de-activate the `Sector` and `Subsector` dropdowns unless a `Domain` is selected. Once a domain is selected, I would dynamically change the options for Sector and enable the Sector drop-down.
* I would leave the Sector and Subsector dropdowns without any options, or set them to '- Any -' (nil) at page load.

**Comment by dragonzzz** [comment]
Sounds perfect. I'll research more into it and report back to how well it work.
Thank you so much. Filterrific has been awesome to work with as are all of the help you have provided me and everyone here.

**Comment by jhund** [comment]
Thanks, I look forward to hearing back from you. And thanks for using Filterrific and your appreciation!
